apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: nextcloud
  annotations:
    # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#traefik-1
    # https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/
    # Do not redirect cloud so that photoprism can WEBDav to it and download images (self-signed TLS certificate)
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
    # traefik.ingress.kubernetes.io/redirect-permanent: 'true'
    traefik.ingress.kubernetes.io/redirect-regex: https://(.*)/.well-known/(card|cal)dav
    traefik.ingress.kubernetes.io/redirect-replacement: https://$1/remote.php/dav/
spec:
  tls:
  - hosts:
    - cloud
    - cloud.local
    - cloud.lan
    - kube
    - kube.local
    - kube.lan
  rules:
  - host: cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-server
            port: 
              number: 80
