# TODO: Add a homepage. Until then, redirect '/' to '/nextcloud' for now
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: nextcloud
spec:
  routes:
  - kind: Rule
    match: PathPrefix(`/`)
    # middlewares:
    # - name: redirect-to-nextcloud
    #   namespace: nextcloud
    # Traefik requires us to put a service here but it can be anything since it never runs because we always redirect
    services:
    # - kind: Service
    #   name: nextcloud-server
    #   namespace: nextcloud
    #   port: 80

    - kind: Service
      name: hello-world
      # namespace: homepage
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  creationTimestamp: null
  name: redirect-to-nextcloud
  namespace: nextcloud
spec:
  redirectRegex:
    regex: https://([a-z.]+)(/)(.+)
    replacement: https://$1/nextcloud/$3

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  # namespace: homepage
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      #   volumeMounts:
      #   - name: hello-world-volume
      #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: hello-world-volume
      #   configMap:
      #     name: hello-world

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data: 
  index.html: |
    <html>
    <head>
      <title>Hello World!</title>
    </head>
    <body>Hello World!</body>
    </html>
  hello.txt: Hello World