apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-server
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: nextcloud-server-pod
  template:
    metadata:
      labels:
        pod-label: nextcloud-server-pod
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:21-apache
        volumeMounts:
        - name: server-storage
          mountPath: /var/www/html
          subPath: server-data
        env:
        # See https://github.com/nextcloud/docker#auto-configuration-via-environment-variables
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_HOST
          value: nextcloud-db

        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: password
        
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "kube kube.local kube.lan cloud cloud.local cloud.lan"
        
        # Force https. Otherwise we keep redirecting to http
        - name: OVERWRITEPROTOCOL
          value: https
        - name: OVERWRITEWEBROOT
          value: '/nextcloud'


      volumes:
      - name: server-storage
        persistentVolumeClaim:
          claimName: nextcloud-shared-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-server
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    pod-label: nextcloud-server-pod
  ports:
  - protocol: TCP
    port: 80
