apiVersion: v1
kind: Namespace
metadata:
  name: photoprism
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals-shared-storage-claim
  namespace: photoprism
  labels:
    app: photoprism
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-shared-storage-claim
  namespace: photoprism
  labels:
    app: photoprism
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
