# https://traefik.io/blog/https-on-kubernetes-using-traefik-proxy/
kind: Secret
apiVersion: v1
metadata:
  name: my-tls-secret
  namespace: nextcloud
data:
  tls.crt: >-
    %%TLS_CRT%%
  tls.key: >-
    %%TLS_KEY%%
type: Opaque
